---
configRepositoryType: file
configRepositoryConfig:
  path: 'test/yaml/complete_configuration.yaml'
  format: yaml
auditBackend: /dev/null
configApiAuthStore: none
refreshIntervalMillis: 1500
port: 8080